### ISSUE TITLE
when loading model, there is the issue: ValueError: The parameter scale_tril has invalid values

### ISSUE THREAD

**Issue by Alan-Qin** [peustr/WCA-Net#1]
https://github.com/peustr/WCA-Net/blob/97bf252b662909fc6564c800f0eba35827c56e80/models.py#L197

- scale_tril (Tensor) – lower-triangular factor of covariance, with positive-valued diagonal (from pytorch document)
I check the self.L and find the diagonals of this matrix have negative values. So, maybe it's the reason. 

Please check it. Thanks!

**Comment by peustr** [comment]
Hi there, sorry but I cannot reproduce the error with my version of Pytorch (1.7.0) and CUDA (10.2).
```
pip freeze | grep torch
torch==1.7.0
torchvision==0.8.1
```
Do you have a similar setup?
